# Generated by Django 6.0.3 on 2026-04-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador da sala', max_length=100, unique=True, verbose_name='Codigo')),
                ('tipo', models.CharField(choices=[('QUARTO', 'Quarto'), ('SALA COMERCIAL', 'Sala Comercial')], default='QUARTO', max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('DISPONÍVEL', 'Disponível para reserva'), ('RESERVADA', 'Reservada')], default='DISPONÍVEL', help_text='Status da sala', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
