# Generated by Django 6.0.4 on 2026-05-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0003_alter_bloco_quantidade'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blocos.bloco'),
        ),
    ]
