# Generated by Django 6.0.3 on 2026-05-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_sala_bloco'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='andar',
            field=models.CharField(blank=True, choices=[('1', 'Primeiro Andar'), ('2', 'Segundo Andar'), ('3', 'Terceiro Andar'), ('4', 'Quarto Andar'), ('5', 'Quinto Andar'), ('6', 'Sexto Andar'), ('7', 'Setimo Andar'), ('8', 'Oitavo Andar')], max_length=50, null=True, verbose_name='Andar'),
        ),
    ]
