# Generated by Django 6.0.4 on 2026-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_sala_andar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='codigo',
            field=models.CharField(help_text='Identificador da sala', max_length=100, verbose_name='Codigo'),
        ),
    ]
