# Generated by Django 6.0.4 on 2026-06-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0004_alter_sala_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='nome',
            field=models.CharField(default='Sala 101', help_text='Nome da sala', max_length=100, verbose_name='Nome'),
        ),
    ]
