# Generated by Django 6.0.4 on 2026-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_sala_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(help_text='Nome da sala', max_length=100, verbose_name='Nome'),
        ),
    ]
