# Generated by Django 6.0.3 on 2026-04-11 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador do bloco', max_length=100, unique=True, verbose_name='Codigo')),
                ('andar', models.CharField(choices=[('1', 'Primeiro Andar'), ('2', 'Segundo Andar'), ('3', 'Terceiro Andar')], help_text='Andar do bloco', max_length=100, verbose_name='Andar')),
                ('quantidade', models.CharField(help_text='Quantidade de salas do bloco(Máx: 15)', max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
            },
        ),
    ]
