# Generated by Django 6.0.3 on 2026-04-11 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='andar',
            field=models.CharField(choices=[('1', 'Primeiro Andar'), ('2', 'Segundo Andar'), ('3', 'Terceiro Andar')], default='1', help_text='Andar do bloco', max_length=100, verbose_name='Andar'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='quantidade',
            field=models.IntegerField(help_text='Quantidade de salas do bloco(Máx: 15)', max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantidade'),
        ),
    ]
