# Generated by Django 6.0.4 on 2026-04-23 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0002_alter_bloco_andar_alter_bloco_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='quantidade',
            field=models.IntegerField(help_text='Quantidade de salas do bloco(Máx: 15)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantidade'),
        ),
    ]
