# Generated by Django 6.0.3 on 2026-05-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0003_alter_bloco_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='andar',
            field=models.CharField(choices=[('1', 'Primeiro Andar'), ('2', 'Segundo Andar'), ('3', 'Terceiro Andar'), ('4', 'Quarto Andar'), ('5', 'Quinto Andar'), ('6', 'Sexto Andar'), ('7', 'Setimo Andar'), ('8', 'Oitavo Andar')], default='1', help_text='Andar do bloco', max_length=100, verbose_name='Andar'),
        ),
    ]
