# Generated by Django 6.0.4 on 2026-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0004_alter_bloco_andar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='nome',
            field=models.CharField(default='Bloco A2', help_text='Nome do bloco', max_length=100, verbose_name='Nome'),
        ),
    ]
