# Generated by Django 6.0.4 on 2026-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0005_bloco_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='nome',
            field=models.CharField(help_text='Nome do bloco', max_length=100, verbose_name='Nome'),
        ),
    ]
