# Generated by Django 6.0.4 on 2026-04-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo do funcionário', max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Apenas números ou formato 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('cargo', models.CharField(choices=[('PORTEIRO', 'Porteiro'), ('GERENTE', 'Gerente')], default='PORTEIRO', max_length=20, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
