# Generated by Django 6.0.4 on 2026-04-09 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pessoa_remove_cliente_cpf_remove_cliente_id_and_more'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.pessoa'),
            preserve_default=False,
        ),
    ]
