# Generated by Django 6.0.3 on 2026-04-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.CharField(help_text='Identificador da chave', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
    ]
