# Generated by Django 6.0.3 on 2026-04-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='status',
            field=models.CharField(choices=[('DISPONÍVEL', 'Disponível para empréstimo'), ('EMPRESTADA', 'Emprestada'), ('EXTRAVIADA', 'Perdida/Danificada')], default='DISPONÍVEL', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='chave',
            name='tipo',
            field=models.CharField(choices=[('BLOCO', 'Bloco'), ('Sala', 'Sala')], default='BLOCO', max_length=50, verbose_name='Tipo'),
        ),
    ]
