# Generated by Django 6.0.3 on 2026-04-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_chave_status_chave_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='codigo',
            field=models.CharField(default=1, help_text='Identificador da chave', max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
