# Generated by Django 6.0.4 on 2026-05-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0003_alter_bloco_quantidade'),
        ('chaves', '0003_chave_codigo_alter_chave_id'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blocos.bloco'),
        ),
        migrations.AddField(
            model_name='chave',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='salas.sala'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='tipo',
            field=models.CharField(choices=[('BLOCO', 'Bloco'), ('SALA', 'Sala')], default='BLOCO', max_length=50, verbose_name='Tipo'),
        ),
    ]
