# Generated by Django 6.0.4 on 2026-05-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0004_chave_bloco_chave_sala_alter_chave_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Identificador'),
        ),
    ]
