# Generated by Django 6.0.4 on 2026-04-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do cliente', max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Apenas números ou formato 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('categoria', models.CharField(choices=[('BRONZE', 'Bronze (1 Reserva)'), ('PRATA', 'Prata (2 Reservas)'), ('OURO', 'Ouro (3 Reservas)')], default='BRONZE', max_length=20, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
