# Generated by Django 6.0.4 on 2026-04-09 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Apenas números ou formato 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.pessoa'),
            preserve_default=False,
        ),
    ]
