# Generated by Django 6.0.4 on 2026-05-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pessoa_remove_cliente_cpf_remove_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
