# Generated by Django 6.0.4 on 2026-04-23 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0003_chave_codigo_alter_chave_id'),
        ('clientes', '0002_pessoa_remove_cliente_cpf_remove_cliente_id_and_more'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Codigo do empréstimo', max_length=100, unique=True, verbose_name='Codigo')),
                ('data_inicio', models.DateTimeField(help_text='Data de Inicio do empréstimo', verbose_name='Data de Inicio')),
                ('data_devolucao', models.DateTimeField(help_text='Data de devolução', verbose_name='Data de devolucao')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO/DEVOLVIDO', 'Finalizado/Devolvido')], default='ATIVO', max_length=50, verbose_name='Status')),
                ('chave', models.ForeignKey(help_text='Código da Chave', on_delete=django.db.models.deletion.PROTECT, related_name='chave', to='chaves.chave', verbose_name='Chave')),
                ('cliente', models.ForeignKey(help_text='Nome do Cliente', on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo_cliente', to='clientes.cliente', verbose_name='Cliente')),
                ('reserva', models.ForeignKey(help_text='Código da reserva', on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='reservas.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
