# Generated by Django 6.0.4 on 2026-05-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0004_chave_bloco_chave_sala_alter_chave_codigo_and_more'),
        ('clientes', '0002_pessoa_remove_cliente_cpf_remove_cliente_id_and_more'),
        ('emprestimos', '0001_initial'),
        ('reservas', '0002_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='chave_bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo_chave_bloco', to='chaves.chave', verbose_name='Chave do Bloco'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='chave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo_chave', to='chaves.chave', verbose_name='Chave da Sala/Quarto'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo_cliente', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo_reserva', to='reservas.reserva'),
        ),
    ]
