# Generated by Django 6.0.4 on 2026-05-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_options_emprestimo_chave_bloco_and_more'),
        ('funcionarios', '0002_remove_funcionario_cpf_remove_funcionario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='funcionario',
            field=models.ForeignKey(blank=True, help_text='Funcionário que entregou a chave', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
    ]
