# Generated by Django 6.0.4 on 2026-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_emprestimo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO/DEVOLVIDO', 'Finalizado/Devolvido'), ('ATRASADO', 'Atrasado')], default='ATIVO', max_length=50, verbose_name='Status'),
        ),
    ]
