# Generated by Django 6.0.4 on 2026-04-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_pessoa_remove_cliente_cpf_remove_cliente_id_and_more'),
        ('funcionarios', '0002_remove_funcionario_cpf_remove_funcionario_id_and_more'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Codigo da reserva', max_length=100, unique=True, verbose_name='Codigo')),
                ('data_inicio', models.DateTimeField(help_text='Data de início da reserva', verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(help_text='Data de fim da reserva', verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=50, verbose_name='Status')),
                ('cliente', models.ForeignKey(help_text='Nome do Cliente', on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='clientes.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(help_text='Nome do Funcionário', on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('sala', models.ForeignKey(help_text='Nome do Cliente', on_delete=django.db.models.deletion.PROTECT, related_name='sala', to='salas.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
