# Generated by Django 6.0.4 on 2026-04-23 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pessoa_remove_cliente_cpf_remove_cliente_id_and_more'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(help_text='Nome do Cliente', on_delete=django.db.models.deletion.PROTECT, related_name='reserva_cliente', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
