# Generated by Django 6.0.4 on 2026-05-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_cliente'),
        ('salas', '0002_sala_bloco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(help_text='Nome da Sala', on_delete=django.db.models.deletion.PROTECT, related_name='sala', to='salas.sala', verbose_name='Sala'),
        ),
    ]
