# Generated by Django 6.0.3 on 2026-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=50, verbose_name='Status'),
        ),
    ]
